project:
  type: website
  output-dir: _site
  render: 
    - "*.qmd"
  resources:
    - .well-known/
    - _headers
    - /assets/fonts/
website:
  description: "A personal website"
  site-url: https://rorylawless.com
  title: "Rory Lawless"
  repo-url: https://gitlab.com/rorylawless/website
  llms-txt: true
  page-footer:
    center: |
      Made with [Quarto](https://quarto.org/) in DC.<br>[Website](https://rorylawless.com/) © 2026 by [Rory Lawless](/about.qmd) is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).
  search: false
  draft-mode: gone
  navbar:
    right:
      - icon: file-earmark-person-fill
        href: resume.qmd
        aria-label: "Rory's Resume"
        text: " "
      - icon: envelope-at-fill
        href: mailto:rory@rorylawless.com
        aria-label: "Email Rory"
      - icon: bluesky
        href: https://bsky.app/profile/rorylawless.com
        aria-label: "Rory's Bluesky"
      - icon: linkedin
        href: https://www.linkedin.com/in/rory-lawless/
        aria-label: "Rory's LinkedIn"
      - icon: gitlab
        href: https://gitlab.com/rorylawless
        aria-label: "Rory's GitLab"
format:
  html:
    theme:
      - none
      - brand
      - assets/custom.scss
    highlight-style: a11y
    code-copy: true
    code-overflow: wrap
    email-obfuscation: references
    include-before-body: html/skip-link.html
    include-after-body: html/a11y.html
    favicon: none
    html-math-method: plain
